apiVersion: apps/v1
kind: Deployment
metadata:
  name: webservice
  labels:
    app: webservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webservice
  template:
    metadata:
      name: webservice
      labels:
        app: webservice
    spec:
      containers:
        - name: webservice
          image: nginx:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      